import Router from "express";
import { userController } from "./student.controller";
import { asyncWrap } from "@/utils/asyncWrap";
import { authenticateToken } from "@/middlewares/auth.middleware";
const userRouter = Router();
userRouter.post("/signup", asyncWrap(userController.signUpUser));
userRouter.post("/login", asyncWrap(userController.login));
userRouter.post("/logout", authenticateToken, asyncWrap(userController.logout));
userRouter.get("/google", asyncWrap(userController.googleLogin));
userRouter.post("/refresh", asyncWrap(userController.refreshToken));
export default userRouter;
